### ISSUE TITLE
Confirmation e-mail not coming

### ISSUE THREAD

**Issue by lubianat** [Mee-Repo/issue#3]
## Description
Confirmation e-mail after registration not coming.

### How to reproduce
1. Go to https://test.mee.cc/auth/join
2. Fill form
3. Hit submit
4. Email does not come.
5. Hit "send again" on https://test.mee.cc/auth/join/verification
6. Email does not come.

![image](https://user-images.githubusercontent.com/7917951/83357687-3aedfb80-a344-11ea-96c0-5ec8045c8518.png)

I am using the mee e-mail tiago.lubiana [arroba] mee.cc
![image](https://user-images.githubusercontent.com/7917951/83357693-42150980-a344-11ea-968c-1fa894bd08f9.png)

It is not in the inbox, it is not in spam.

### Expected Behaviour
Getting an e-mail with the code.

## Environment details
| environment  | data                                           |
| ------------ |:---------------------------------------------- |
| hostname     | test.mee.cc                                 |
| mode         | production                                     |
| build time   | 2020-05-28T22:29:10.968Z          |
| app version  | 1.0.0-setup.0                               |
| commit       | 449a3adcf41326d0540481d2f47caf7d43bf5b9f       |
| device type  |Laptop Computer    |
| os           | Ubuntu             |
| os version   | 18.04           |
| browser      | Firefox           |
| browser ver. | 76.0.1 (64-bit)           |

**Comment by GuiAzzi** [comment]
Retest requested on Slack after https://github.com/Mee-Repo/Mee-WebClient/commit/0404aa23dbedf1b5b1bb5a9134514aeecf016e53

**Comment by lubianat** [comment]
It worked now (same configs, different build, private firefox window)

**Comment by lubianat** [comment]
| environment  | data                                           |
| ------------ |:---------------------------------------------- |
| hostname     | test.mee.cc                                    |
| api URL      | https://api.mee.cc/test                        |
| mode         | production                                     |
| build time   | 2020-06-10T18:31:07.467Z                       |
| app version  | 1.0.0-setup.0                                  |
| commit       | 0404aa23dbedf1b5b1bb5a9134514aeecf016e53       |
| device type  | [fill this for report e.g. Macbook, iPhone XR] |
| os           | Ubuntu                                         |
| os version   | none                                           |
| browser      | Firefox                                        |
| browser ver. | 77.0                                           |

**Comment by lubianat** [comment]
I had entered a wrong e-mail, and fixed after retrying (but without changing the user name). This might somehow have messed with cache (I do not know how) .
